[workspace]
members = ["macroslib", "jni_tests", "cpp_tests", "android-example", "android-tests",
"debug-util", "cpp-example/rust-part", "python_tests", "dotnet_tests"]

[profile.release]
debug = true
incremental = true
